### ISSUE TITLE
Fails to build with newer versions of node

### ISSUE THREAD

**Issue by kellyrob99** [sonatype/ui-gallery#41]
I experienced issues trying to utilize the gallery locally on mac and ended up having to go all the way back to node V6.17.1 (which reached EOL in 2019) to find a version that would work for me.
Tried with v12.8.0 and v14.5.0 specifically, neither of which would build. 
I'm assuming that this is intended to work with newer versions of node given that the minimum suggested version from the docs is v6.5.0 (which is now 5 years old)?

**log snippet from v12.8.0 attempt:** 
`21902 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
21903 verbose optional SKIPPING OPTIONAL DEPENDENCY:
21903 verbose optional Failed at the fsevents@1.2.4 install script.
21903 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
21904 verbose stack Error: node-sass@4.5.3 postinstall: `node scripts/build.js`
21904 verbose stack Exit status 1
21904 verbose stack     at EventEmitter.<anonymous> (/Users/krobinson/.nvm/versions/node/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
21904 verbose stack     at EventEmitter.emit (events.js:203:13)
21904 verbose stack     at ChildProcess.<anonymous> (/Users/krobinson/.nvm/versions/node/v12.8.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
21904 verbose stack     at ChildProcess.emit (events.js:203:13)
21904 verbose stack     at maybeClose (internal/child_process.js:1021:16)
21904 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
21905 verbose pkgid node-sass@4.5.3
21906 verbose cwd /Users/krobinson/github/sonatype/ui-gallery
21907 verbose Darwin 17.7.0
21908 verbose argv "/Users/krobinson/.nvm/versions/node/v12.8.0/bin/node" "/Users/krobinson/.nvm/versions/node/v12.8.0/lib/node_modules/npm/bin/npm-cli.js" "install" "--scripts-prepend-node-path=auto"
21909 verbose node v12.8.0
21910 verbose npm  v6.10.2
21911 error code ELIFECYCLE
21912 error errno 1
21913 error node-sass@4.5.3 postinstall: `node scripts/build.js`
21913 error Exit status 1
21914 error Failed at the node-sass@4.5.3 postinstall script.
21914 error This is probably not a problem with npm. There is likely additional logging output above.
21915 verbose exit [ 1, true ]`

**log snippet from v12.8.0 attempt:** 
`21880 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
21881 verbose optional SKIPPING OPTIONAL DEPENDENCY:
21881 verbose optional Failed at the fsevents@1.2.4 install script.
21881 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
21882 verbose stack Error: node-sass@4.5.3 postinstall: `node scripts/build.js`
21882 verbose stack Exit status 1
21882 verbose stack     at EventEmitter.<anonymous> (/Users/krobinson/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
21882 verbose stack     at EventEmitter.emit (events.js:314:20)
21882 verbose stack     at ChildProcess.<anonymous> (/Users/krobinson/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
21882 verbose stack     at ChildProcess.emit (events.js:314:20)
21882 verbose stack     at maybeClose (internal/child_process.js:1051:16)
21882 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
21883 verbose pkgid node-sass@4.5.3
21884 verbose cwd /Users/krobinson/github/sonatype/ui-gallery
21885 verbose Darwin 17.7.0
21886 verbose argv "/Users/krobinson/.nvm/versions/node/v14.5.0/bin/node" "/Users/krobinson/.nvm/versions/node/v14.5.0/bin/npm" "install"
21887 verbose node v14.5.0
21888 verbose npm  v6.14.5
21889 error code ELIFECYCLE
21890 error errno 1
21891 error node-sass@4.5.3 postinstall: `node scripts/build.js`
21891 error Exit status 1
21892 error Failed at the node-sass@4.5.3 postinstall script.
21892 error This is probably not a problem with npm. There is likely additional logging output above.
21893 verbose exit [ 1, true ]`

**Comment by rpokorny** [comment]
If I'm not mistaken this repo is deprecated.  @glenhunter is that correct?  If you are looking for the React Shared Components, they are in https://github.com/sonatype/sonatype-react-shared-components

**Comment by kellyrob99** [comment]
> If I'm not mistaken this repo is deprecated. @glenhunter is that correct? If you are looking for the React Shared Components, they are in https://github.com/sonatype/sonatype-react-shared-components

Yes indeed, Glen has steered me there already tyvm :D
